### ISSUE TITLE
German page is still 6.5.20

### ISSUE THREAD

**Issue by stejan** [AdobeDocs/experience-manager-65.de-DE#5] opened 2024-08-30 09:57 UTC
Issue in ./help/release-notes/release-notes.md

the german translation is still 6.5.20
the english is correct

![image](https://github.com/user-attachments/assets/7256c9c0-e444-4514-a6bd-adcf94789a7c)

**Comment by jonsamhudec** [comment] 2024-09-11 16:21
The issue in German was already updated, unfortunately there is an issue with publishing process affecting the live page. It was reported to responsible team and is being worked on. Tracked under UGP-11793.

**Comment by jonsamhudec** [comment] 2024-09-17 08:16
The issue is now fixed.

**Closed as completed by jonsamhudec** 2024-09-17 08:16 UTC
